# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ad1d307f69d0d9992aa9fcc1a5a283d20667e831488ed96f1751e1bf4eb0b1198a620978f3644532775c55f6823afc9a261ed9a26715737a5f91b0e0914ea0

test:
  secret_key_base: 51f80dda1417436539b8692a9f85674e389a401e0fd7992e171460892a3b6e29f68990f50afb6780d3a802ed37241ced8d2fa75092a8540534b2f016b1828087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
